const test=require('node:test');
const assert=require('node:assert/strict');
const {buildAIContext,needsConfirmation,validatePlan,createAITaskManager}=require('../electron/ai-core.cjs');

test('AI context contains IDs and metadata but never exposes the local library path',()=>{const context=buildAIContext({name:'AX17',path:'S:/secret',folders:[{id:'f',name:'05_场景'}],assets:[{id:'a',name:'书房',tags:[]}]},{folderId:'f',selectedIds:['a']});assert.equal(context.library.name,'AX17');assert.equal('path' in context.library,false);assert.equal(JSON.stringify(context).includes('S:/secret'),false);assert.equal(context.selectedAssets[0].id,'a')});
test('permission layer cannot be bypassed by model supplied risk flags',()=>{const plan=validatePlan({actions:[{tool:'move_asset',assetId:'a',targetFolderId:'f',risk:'LOW',requiresConfirmation:false}]},{assets:[{id:'a'}],folders:[{id:'f'}]});assert.equal(plan.actions[0].risk,'HIGH');assert.equal(plan.actions[0].requiresConfirmation,true);assert.equal(needsConfirmation('add_tags'),true)});
test('V1 rejects destructive or unknown tools even if confirmed by a caller',()=>{assert.throws(()=>validatePlan({actions:[{tool:'delete_asset',assetId:'a'}]},{assets:[{id:'a'}],folders:[]}),/禁止|支持/);assert.throws(()=>validatePlan({actions:[{tool:'fs_rm',assetId:'a'}]},{assets:[{id:'a'}],folders:[]}),/禁止|支持/)});
test('task manager enforces concurrency and cancellation',async()=>{const manager=createAITaskManager({concurrency:1}),events=[];let release;const gate=new Promise(resolve=>{release=resolve});const first=manager.create(async()=>{events.push('first');await gate;return 1}),second=manager.create(async()=>{events.push('second');return 2});assert.equal(manager.get(first).status,'running');assert.equal(manager.get(second).status,'queued');assert.equal(manager.cancel(second),true);release();await new Promise(resolve=>setTimeout(resolve,20));assert.deepEqual(events,['first']);assert.equal(manager.get(first).status,'completed');assert.equal(manager.get(second).status,'cancelled')});
test('queued tasks can pause and resume without consuming a worker',async()=>{const manager=createAITaskManager({concurrency:1});let release;const gate=new Promise(resolve=>{release=resolve});manager.create(async()=>gate);const id=manager.create(async()=>42);assert.equal(manager.pause(id),true);assert.equal(manager.get(id).status,'paused');assert.equal(manager.resume(id),true);release();await new Promise(resolve=>setTimeout(resolve,30));assert.equal(manager.get(id).status,'completed');assert.equal(manager.get(id).result,42)});
test('running tasks pause cooperatively and resume with a fresh abort signal',async()=>{const manager=createAITaskManager({concurrency:1});let runs=0,markStarted;const started=new Promise(resolve=>{markStarted=resolve});const id=manager.create(({signal})=>new Promise((resolve,reject)=>{runs++;markStarted();if(runs>1)return resolve('done');signal.addEventListener('abort',()=>reject(new Error('paused')),{once:true})}));await started;assert.equal(manager.pause(id),true);await new Promise(resolve=>setTimeout(resolve,10));assert.equal(manager.get(id).status,'paused');assert.equal(manager.resume(id),true);await new Promise(resolve=>setTimeout(resolve,20));assert.equal(manager.get(id).status,'completed');assert.equal(manager.get(id).attempts,2)});
test('failed tasks can be retried as a separately auditable task',async()=>{const manager=createAITaskManager();let attempts=0;const id=manager.create(async()=>{if(!attempts++)throw new Error('temporary');return'ok'});await new Promise(resolve=>setTimeout(resolve,10));assert.equal(manager.get(id).status,'failed');const retry=manager.retry(id);assert.ok(retry);await new Promise(resolve=>setTimeout(resolve,10));assert.equal(manager.get(retry).status,'completed');assert.equal(manager.get(retry).meta.retryOf,id)});
