const { app, BrowserWindow, clipboard, dialog, ipcMain, nativeImage, net, protocol, shell } = require('electron');
const { pathToFileURL } = require('url');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const http = require('http');
const { spawn } = require('child_process');
const { Readable } = require('stream');
const { atomicWriteJson, readJson } = require('./json-storage.cjs');
const { expandImportPaths } = require('./import-paths.cjs');
const { chooseReadableFilename } = require('./asset-filenames.cjs');
const { collectFolderSubtreeIds } = require('./folder-tree.cjs');
const { folderParts, physicalAssetPath, syncPhysicalFolders } = require('./physical-folders.cjs');
const { createDuplicateIndex, isDuplicate, recordHash } = require('./import-duplicates.cjs');

protocol.registerSchemesAsPrivileged([{ scheme: 'nest', privileges: { standard: true, secure: true, supportFetchAPI: true, corsEnabled: true } }]);
const gotSingleInstanceLock = app.requestSingleInstanceLock();
if (!gotSingleInstanceLock) app.quit();
app.on('second-instance', () => { const win = BrowserWindow.getAllWindows()[0]; if (win) { if (win.isMinimized()) win.restore(); win.show(); win.focus(); } });
let libraryPath = null;
const settingsFile = () => path.join(app.getPath('userData'), 'settings.json');
const indexFile = root => path.join(root, '.nest-library.json');
const assetsDir = root => path.join(root, 'assets');
const storedAssetPath = file => physicalAssetPath(libraryPath, file);
const writeJson = (file, value) => atomicWriteJson(file, value);
const saveSettings = () => writeJson(settingsFile(), { libraryPath });
const readLibrary = () => {if(!libraryPath)return null;const data=readJson(indexFile(libraryPath));if(!data)return null;return{...data,folders:Array.isArray(data.folders)?data.folders:[],tags:Array.isArray(data.tags)?data.tags:[],assets:(Array.isArray(data.assets)?data.assets:[]).filter(Boolean).map(a=>({...a,name:String(a.name||a.originalName||'未命名素材'),tags:Array.isArray(a.tags)?a.tags:[],favorite:Boolean(a.favorite),rating:Number(a.rating)||0}))}};
const publicLibrary = data => data ? { ...data, path: libraryPath, assets: data.assets.map(a => ({ ...a, url: a.file?`nest://asset/${encodeURIComponent(a.file)}`:'' })) } : null;
function backupLibrary(){if(!libraryPath||!fs.existsSync(indexFile(libraryPath)))return;const dir=path.join(libraryPath,'.nest-backups');fs.mkdirSync(dir,{recursive:true});const day=new Date().toISOString().slice(0,10);const target=path.join(dir,`library-${day}.json`);if(!fs.existsSync(target))fs.copyFileSync(indexFile(libraryPath),target)}

function initializeLibrary(root) {
  fs.mkdirSync(root, { recursive: true }); fs.mkdirSync(assetsDir(root), { recursive: true });
  if (!fs.existsSync(indexFile(root))) writeJson(indexFile(root), { version: 1, name: path.basename(root), folders: [], tags: [], assets: [], createdAt: Date.now() });
  libraryPath = root; saveSettings(); backupLibrary(); return publicLibrary(readLibrary());
}
async function selectFolder(title) { const r = await dialog.showOpenDialog({ title, properties: ['openDirectory', 'createDirectory'] }); return r.canceled ? null : r.filePaths[0]; }

ipcMain.handle('library:current', () => { const saved = readJson(settingsFile()); if (!libraryPath && saved?.libraryPath && fs.existsSync(indexFile(saved.libraryPath))) libraryPath = saved.libraryPath; backupLibrary(); const data=readLibrary();if(data){syncPhysicalFolders(libraryPath,data);writeJson(indexFile(libraryPath),data)}return publicLibrary(data); });
ipcMain.handle('library:create', async () => { const root = await selectFolder('选择或新建 Nest 资源库文件夹'); return root ? initializeLibrary(root) : null; });
ipcMain.handle('library:open', async () => { const root = await selectFolder('打开小旺仔资源库'); if (!root) return null; if (!fs.existsSync(indexFile(root))) return { error: '所选文件夹不是小旺仔资源库' }; libraryPath = root; saveSettings(); backupLibrary(); const data=readLibrary();syncPhysicalFolders(libraryPath,data);writeJson(indexFile(libraryPath),data);return publicLibrary(data); });
ipcMain.handle('library:health', () => {const data=readLibrary();if(!data)return null;const missing=data.assets.filter(a=>!a.file||!fs.existsSync(storedAssetPath(a.file))).map(a=>({id:a.id,name:a.name,file:a.file||''}));return{missing,total:data.assets.length,backupDir:path.join(libraryPath,'.nest-backups')}});
ipcMain.handle('library:repair', () => {const data=readLibrary();if(!data)return null;backupLibrary();data.folders=Array.isArray(data.folders)?data.folders:[];data.assets=(Array.isArray(data.assets)?data.assets:[]).filter(a=>a?.id&&a?.file&&fs.existsSync(storedAssetPath(a.file))).map(a=>({...a,tags:Array.isArray(a.tags)?a.tags:[]}));syncPhysicalFolders(libraryPath,data);writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
ipcMain.handle('library:add-folder', (_, options) => {const data=readLibrary();if(!data)return null;const clean=String(options?.name||'').trim().slice(0,50),parentId=options?.parentId||null;if(!clean)return{error:'文件夹名称不能为空'};if(parentId&&!data.folders.some(f=>f.id===parentId))return{error:'所选父级文件夹不存在'};if(data.folders.some(f=>f.name===clean&&(f.parentId||null)===parentId))return{error:'同一级中已存在同名文件夹'};data.folders.push({id:crypto.randomUUID(),name:clean,parentId,icon:String(options?.icon||'folder'),color:String(options?.color||'#8f98a3'),createdAt:Date.now()});syncPhysicalFolders(libraryPath,data);writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
ipcMain.handle('library:update-folder', (_, id, changes) => {const data=readLibrary();if(!data)return null;const current=data.folders.find(f=>f.id===id);if(!current)return{error:'文件夹不存在或已被删除'};const clean=String(changes?.name??current.name).trim(),parentId=changes?.parentId===undefined?(current.parentId||null):(changes.parentId||null);if(!clean)return{error:'文件夹名称不能为空'};if(parentId===id)return{error:'文件夹不能移动到自身'};const descendants=new Set([id]);for(let changed=true;changed;){changed=false;for(const folder of data.folders)if(folder.parentId&&descendants.has(folder.parentId)&&!descendants.has(folder.id)){descendants.add(folder.id);changed=true}}if(parentId&&(!data.folders.some(f=>f.id===parentId)||descendants.has(parentId)))return{error:'不能移动到自身或子文件夹'};if(data.folders.some(f=>f.id!==id&&f.name===clean&&(f.parentId||null)===parentId))return{error:'同一级中已存在同名文件夹'};data.folders=data.folders.map(f=>f.id===id?{...f,...changes,name:clean,parentId,id:f.id}:f);syncPhysicalFolders(libraryPath,data);writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
ipcMain.handle('library:delete-folder', async (_, id) => {const data=readLibrary();if(!data)return null;if(!data.folders.some(folder=>folder.id===id))return{error:'文件夹不存在或已被删除'};const folderIds=collectFolderSubtreeIds(data.folders,id),targets=data.assets.filter(asset=>folderIds.has(asset.folderId)),removedAssetIds=new Set(),errors=[];for(const asset of targets){try{const target=storedAssetPath(asset.file);if(asset.file&&fs.existsSync(target))await shell.trashItem(target);removedAssetIds.add(asset.id)}catch(error){errors.push(`${asset.name}: ${error.message}`)}}data.assets=data.assets.filter(asset=>!removedAssetIds.has(asset.id));if(!errors.length)data.folders=data.folders.filter(folder=>!folderIds.has(folder.id));syncPhysicalFolders(libraryPath,data);data.lastDelete={kind:'folder',folderId:id,removedAssets:removedAssetIds.size,removedFolders:errors.length?0:folderIds.size,errors,completed:errors.length===0,finishedAt:Date.now()};writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
ipcMain.handle('library:add-tag', (_, name) => {const data=readLibrary();if(!data)return null;const clean=String(name||'').trim();data.tags=Array.isArray(data.tags)?data.tags:[];if(clean&&!data.tags.includes(clean))data.tags.push(clean);writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
ipcMain.handle('library:delete-tag', (_, name) => {const data=readLibrary();if(!data)return null;data.tags=data.tags.filter(t=>t!==name);data.assets=data.assets.map(a=>({...a,tags:a.tags.filter(t=>t!==name)}));writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
const hashFile = file => new Promise((resolve, reject) => { const hash=crypto.createHash('sha256'); const stream=fs.createReadStream(file); stream.on('data',chunk=>hash.update(chunk)); stream.on('error',reject); stream.on('end',()=>resolve(hash.digest('hex'))); });
function readableAssetFilename(data, displayName, extension, excludeId = null) {
  let candidate = chooseReadableFilename(data.assets, displayName, extension, excludeId);
  const base = path.basename(candidate, extension);
  for (let number = 2; fs.existsSync(path.join(assetsDir(libraryPath), candidate)) && !data.assets.some(asset => asset.id === excludeId && path.basename(asset.file).toLowerCase() === candidate.toLowerCase()); number += 1) candidate = `${base} (${number})${extension}`;
  return candidate;
}
function migrateAssetFilename(data, asset, displayName = asset.name) {
  const oldRelative = asset.file || '', oldFile = path.basename(oldRelative);
  if (!oldFile) throw new Error('素材文件名为空');
  const extension = path.extname(oldFile).toLowerCase();
  const newFile = readableAssetFilename(data, displayName, extension, asset.id);
  if (oldFile.toLowerCase() === newFile.toLowerCase()) return false;
  const source = storedAssetPath(oldRelative), relativeDir=path.dirname(oldRelative)==='.'?'':path.dirname(oldRelative);
  if (!fs.existsSync(source)) throw new Error('素材原文件不存在');
  const nextRelative=path.join(relativeDir,newFile).replace(/\\/g,'/');fs.renameSync(source, storedAssetPath(nextRelative));
  asset.file = nextRelative;
  asset.originalName = newFile;
  return true;
}
async function responseToBuffer(response, maxBytes = 50 * 1024 * 1024) { const length=Number(response.headers.get('content-length')||0);if(length>maxBytes)throw new Error('图片超过 50 MB');if(!response.body)return Buffer.alloc(0);const reader=response.body.getReader(),chunks=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new Error('图片超过 50 MB')}chunks.push(Buffer.from(value))}}finally{reader.releaseLock()}return Buffer.concat(chunks,size) }
async function importPaths(paths, folderId = null, { preserveFolders = false } = {}) {
  const data=readLibrary();if(!data)return null;if(folderId&&!data.folders.some(folder=>folder.id===folderId))return{error:'目标文件夹不存在或已被删除'};let imported=0,duplicates=0;const expanded=await expandImportPaths(paths),errors=[...expanded.errors],duplicateIndex=createDuplicateIndex(data.assets);
  const ensureFolderPath=parts=>{let parentId=folderId;for(const part of parts){const name=String(part||'').trim().slice(0,50)||'未命名文件夹';let folder=data.folders.find(item=>item.name===name&&(item.parentId||null)===(parentId||null));if(!folder){folder={id:crypto.randomUUID(),name,parentId:parentId||null,icon:'folder',color:'#8f98a3',createdAt:Date.now()};data.folders.push(folder)}parentId=folder.id}syncPhysicalFolders(libraryPath,data);return parentId};
  if(preserveFolders)for(const parts of expanded.directories)ensureFolderPath(parts);
  for(const entry of expanded.entries){const source=entry.file,destinationFolderId=preserveFolders?ensureFolderPath(entry.folders):folderId;try{const stat=await fs.promises.stat(source);const ext=path.extname(source).toLowerCase();const imageExts=['.jpg','.jpeg','.png','.gif','.webp','.svg','.bmp','.avif'];const videoExts=['.mp4','.webm','.mov','.m4v'];const audioTypes={'.mp3':'audio/mpeg','.wav':'audio/wav','.flac':'audio/flac','.aac':'audio/aac','.m4a':'audio/mp4','.ogg':'audio/ogg','.opus':'audio/ogg','.wma':'audio/x-ms-wma'};if(![...imageExts,...videoExts,...Object.keys(audioTypes)].includes(ext))throw new Error('不支持的格式');const hash=await hashFile(source);if(isDuplicate(duplicateIndex,hash,destinationFolderId,preserveFolders)){duplicates++;continue}const file=readableAssetFilename(data,path.basename(source,ext),ext);await fs.promises.copyFile(source,path.join(assetsDir(libraryPath),file));const type=imageExts.includes(ext)?`image/${ext.slice(1).replace('jpg','jpeg')}`:videoExts.includes(ext)?`video/${ext.slice(1).replace('mov','quicktime')}`:audioTypes[ext];data.assets.unshift({id:crypto.randomUUID(),file,name:path.basename(source,ext),originalName:path.basename(source),type,size:stat.size,width:0,height:0,tags:[],favorite:false,note:'',rating:0,folderId:destinationFolderId,hash,createdAt:Date.now(),modifiedAt:Date.now()});recordHash(duplicateIndex,hash,destinationFolderId);imported++}catch(error){errors.push(`${path.basename(source)}: ${error.message}`)}}
  syncPhysicalFolders(libraryPath,data);data.lastImport={imported,duplicates,errors,finishedAt:Date.now()};writeJson(indexFile(libraryPath),data);return publicLibrary(data);
}
function notifyLibraryChanged(data){for(const win of BrowserWindow.getAllWindows())win.webContents.send('library:changed',publicLibrary(data))}
function startClipServer(){const server=http.createServer(async(req,res)=>{const origin=req.headers.origin||'';const allowed=origin.startsWith('chrome-extension://');res.setHeader('Access-Control-Allow-Origin',allowed?origin:'null');res.setHeader('Access-Control-Allow-Headers','content-type,x-nest-name');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(req.method!=='POST'||!allowed){res.writeHead(403);return res.end('Forbidden')}if(!libraryPath){res.writeHead(409);return res.end('请先启动 Nest 并打开资源库')}if(req.url==='/clip-data'){const mime=String(req.headers['content-type']||'').split(';')[0].toLowerCase(),map={'image/jpeg':'.jpg','image/png':'.png','image/gif':'.gif','image/webp':'.webp','image/svg+xml':'.svg','image/avif':'.avif','image/bmp':'.bmp'};if(!map[mime]){res.writeHead(415);return res.end(`不支持的图片格式：${mime||'未知'}`)}let size=0,temp;const chunks=[];req.on('data',chunk=>{size+=chunk.length;if(size>50*1024*1024)req.destroy(new Error('图片超过 50 MB'));else chunks.push(chunk)});req.on('error',error=>{if(!res.headersSent){res.writeHead(413);res.end(error.message)}});req.on('end',async()=>{try{const raw=decodeURIComponent(String(req.headers['x-nest-name']||'网页图片')).replace(/[\\/:*?"<>|]/g,'_').slice(0,120)||'网页图片';temp=path.join(app.getPath('temp'),`${raw.replace(/\.[^.]+$/,'')}-${crypto.randomUUID()}${map[mime]}`);await fs.promises.writeFile(temp,Buffer.concat(chunks));const result=await importPaths([temp],null);notifyLibraryChanged(result);res.setHeader('content-type','application/json');res.end(JSON.stringify(result?.lastImport||{}))}catch(error){res.writeHead(400);res.end(error.message)}finally{if(temp)await fs.promises.rm(temp,{force:true}).catch(()=>{})}});return}if(req.url!=='/clip'){res.writeHead(404);return res.end('Not found')}let body='';req.on('data',chunk=>{body+=chunk;if(body.length>10000)req.destroy()});req.on('end',async()=>{let temp;try{const {url}=JSON.parse(body);const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw new Error('仅支持网页图片');const response=await fetch(url);if(!response.ok)throw new Error(`下载失败 ${response.status}`);const mime=(response.headers.get('content-type')||'').split(';')[0];const map={'image/jpeg':'.jpg','image/png':'.png','image/gif':'.gif','image/webp':'.webp','image/svg+xml':'.svg','image/avif':'.avif'};if(!map[mime])throw new Error('网页内容不是支持的图片');temp=path.join(app.getPath('temp'),`nest-clip-${crypto.randomUUID()}${map[mime]}`);await fs.promises.writeFile(temp,await responseToBuffer(response));const result=await importPaths([temp],null);notifyLibraryChanged(result);res.setHeader('content-type','application/json');res.end(JSON.stringify(result?.lastImport||{}))}catch(error){res.writeHead(400);res.end(error.message)}finally{if(temp)await fs.promises.rm(temp,{force:true}).catch(()=>{})}})});server.on('error',error=>{if(error.code!=='EADDRINUSE')console.error('Clip server:',error)});server.listen(32145,'127.0.0.1');return server}
ipcMain.handle('library:import', async (_, folderId = null) => { const data=readLibrary();if(!data)return null;const r=await dialog.showOpenDialog({title:'导入素材',properties:['openFile','multiSelections'],filters:[{name:'图片、视频与音频',extensions:['jpg','jpeg','png','gif','webp','svg','bmp','avif','mp4','webm','mov','m4v','mp3','wav','flac','aac','m4a','ogg','opus','wma']}]});return r.canceled?publicLibrary(data):importPaths(r.filePaths,folderId); });
ipcMain.handle('library:import-dropped', (_, paths, folderId = null) => {if(paths.length)return importPaths(paths,folderId,{preserveFolders:true});const data=readLibrary();if(!data)return null;data.lastImport={imported:0,duplicates:0,errors:['浏览器没有提供图片网址，请从图片本身拖入，或使用 Nest 网页采集扩展'],finishedAt:Date.now()};return publicLibrary(data)});
ipcMain.handle('library:import-url', async (_, url, folderId = null) => {let temp;try{if(!libraryPath)return null;const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw new Error('仅支持网页图片网址');const response=await fetch(url);if(!response.ok)throw new Error(`下载失败 ${response.status}`);const mime=(response.headers.get('content-type')||'').split(';')[0].toLowerCase();const map={'image/jpeg':'.jpg','image/png':'.png','image/gif':'.gif','image/webp':'.webp','image/svg+xml':'.svg','image/avif':'.avif','image/bmp':'.bmp'};if(!map[mime])throw new Error('拖入的网页内容不是支持的图片');temp=path.join(app.getPath('temp'),`nest-drop-${crypto.randomUUID()}${map[mime]}`);await fs.promises.writeFile(temp,await responseToBuffer(response));return await importPaths([temp],folderId)}catch(error){const data=readLibrary();if(!data)return{error:error.message};data.lastImport={imported:0,duplicates:0,errors:[error.message],finishedAt:Date.now()};return publicLibrary(data)}finally{if(temp)await fs.promises.rm(temp,{force:true}).catch(()=>{})}});
ipcMain.handle('library:open-asset', async (_, id) => {const asset=readLibrary()?.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{const error=await shell.openPath(storedAssetPath(asset.file));return error?{error:`无法打开素材：${error}`}:{ok:true}}catch(error){return{error:`无法打开素材：${error.message}`}}});
ipcMain.handle('library:reveal-asset', (_, id, migrate = false) => {const data=readLibrary(),asset=data?.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{if(migrate&&migrateAssetFilename(data,asset))writeJson(indexFile(libraryPath),data);shell.showItemInFolder(storedAssetPath(asset.file));return{ok:true,library:publicLibrary(data)}}catch(error){return{error:`无法在资源管理器中显示：${error.message}`}}});
ipcMain.handle('library:copy-path', (_, id) => {const data=readLibrary(),asset=data?.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{if(migrateAssetFilename(data,asset))writeJson(indexFile(libraryPath),data);clipboard.writeText(storedAssetPath(asset.file));return{ok:true,library:publicLibrary(data)}}catch(error){return{error:`无法复制路径：${error.message}`}}});
ipcMain.handle('library:copy-folder-path', (_, id) => {const asset=readLibrary()?.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{clipboard.writeText(path.dirname(storedAssetPath(asset.file)));return{ok:true}}catch(error){return{error:`无法复制所在目录：${error.message}`}}});
ipcMain.handle('library:copy-asset', async (_, id) => {const asset=readLibrary()?.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{const file=storedAssetPath(asset.file);if(!fs.existsSync(file))return{error:'素材原文件不存在'};if(process.platform==='win32'){const encoded=Buffer.from(file,'utf8').toString('base64');const script=`Add-Type -AssemblyName System.Windows.Forms;$p=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${encoded}'));$files=New-Object System.Collections.Specialized.StringCollection;$files.Add($p)>$null;[Windows.Forms.Clipboard]::SetFileDropList($files)`;await new Promise((resolve,reject)=>{const child=spawn('powershell.exe',['-STA','-NoProfile','-NonInteractive','-Command',script],{windowsHide:true});let error='';child.stderr.on('data',chunk=>error+=chunk);child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error(error.trim()||`PowerShell exited with code ${code}`)))})}else clipboard.writeText(file);return{ok:true,kind:'file'}}catch(error){return{error:`复制文件失败：${error.message}`}}});
ipcMain.handle('app:open-bug-feedback', event => {try{const parent=BrowserWindow.fromWebContents(event.sender);const existing=BrowserWindow.getAllWindows().find(win=>win.__nestBugFeedback);if(existing){existing.show();existing.focus();return{ok:true}}const win=new BrowserWindow({width:1080,height:760,minWidth:720,minHeight:520,title:'小旺仔素材库 · Bug 反馈',parent:parent||undefined,icon:path.join(app.getAppPath(),'build','icon.png'),backgroundColor:'#15191e',webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});win.__nestBugFeedback=true;win.loadURL('https://docs.qq.com/form/page/DV2JNUUd3cEVqSHZt');win.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/.test(url)){win.loadURL(url);return{action:'deny'}}return{action:'deny'}});return{ok:true}}catch(error){return{error:`无法打开 Bug 反馈：${error.message}`}}});
ipcMain.on('library:start-external-drag', (event, requestedIds) => {try{const data=readLibrary(),ids=new Set(Array.isArray(requestedIds)?requestedIds:[requestedIds]),assets=data?.assets.filter(item=>ids.has(item.id)&&item.file)||[];if(!data||!assets.length)return;let renamed=false;for(const asset of assets){try{renamed=migrateAssetFilename(data,asset)||renamed}catch(error){console.warn(`Drag filename migration skipped for ${asset.name}:`,error.message)}}if(renamed)writeJson(indexFile(libraryPath),data);const files=assets.map(asset=>storedAssetPath(asset.file)).filter(file=>fs.existsSync(file));if(!files.length)return;const iconPath=path.join(app.getAppPath(),'build','icon.png'),dragIcon=nativeImage.createFromPath(iconPath);if(dragIcon.isEmpty())throw new Error(`拖拽图标无法读取：${iconPath}`);const dragOptions={file:files[0],icon:dragIcon.resize({width:32,height:32,quality:'best'})};if(files.length>1)dragOptions.files=files;event.sender.startDrag(dragOptions)}catch(error){console.error('External drag:',error);if(!event.sender.isDestroyed())event.sender.send('library:external-drag-error',error.message)}});
ipcMain.handle('library:export-asset', async (_, id) => {const asset=readLibrary()?.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{const result=await dialog.showSaveDialog({title:'导出原始文件',defaultPath:asset.originalName||`${asset.name}${path.extname(asset.file)}`});if(result.canceled||!result.filePath)return{canceled:true};await fs.promises.copyFile(storedAssetPath(asset.file),result.filePath);return{ok:true,filePath:result.filePath}}catch(error){return{error:`导出失败：${error.message}`}}});
ipcMain.handle('library:duplicate-asset', async (_, id) => {const data=readLibrary();if(!data)return null;const asset=data.assets.find(a=>a.id===id);if(!asset)return{error:'素材不存在或已被删除'};try{const ext=path.extname(asset.file),name=`${asset.name} 副本`,file=readableAssetFilename(data,name,ext);await fs.promises.copyFile(storedAssetPath(asset.file),storedAssetPath(file));data.assets.unshift({...asset,id:crypto.randomUUID(),file,name,originalName:file,favorite:false,createdAt:Date.now(),modifiedAt:Date.now()});writeJson(indexFile(libraryPath),data);return publicLibrary(data)}catch(error){return{error:`复制素材失败：${error.message}`}}});
ipcMain.handle('extension:prepare', async (_, browser) => {const macApplications='/Applications',choices={chrome:{name:'Google Chrome',url:'chrome://extensions',paths:process.platform==='darwin'?[path.join(macApplications,'Google Chrome.app','Contents','MacOS','Google Chrome')]:[path.join(process.env.PROGRAMFILES||'', 'Google','Chrome','Application','chrome.exe'),path.join(process.env['PROGRAMFILES(X86)']||'', 'Google','Chrome','Application','chrome.exe'),path.join(process.env.LOCALAPPDATA||'', 'Google','Chrome','Application','chrome.exe')]},edge:{name:'Microsoft Edge',url:'edge://extensions',paths:process.platform==='darwin'?[path.join(macApplications,'Microsoft Edge.app','Contents','MacOS','Microsoft Edge')]:[path.join(process.env['PROGRAMFILES(X86)']||'', 'Microsoft','Edge','Application','msedge.exe'),path.join(process.env.PROGRAMFILES||'', 'Microsoft','Edge','Application','msedge.exe')]}};const choice=choices[browser];if(!choice)return{ok:false,error:'不支持的浏览器'};const source=app.isPackaged?path.join(process.resourcesPath,'app.asar.unpacked','browser-extension'):path.join(app.getAppPath(),'browser-extension'),target=path.join(app.getPath('userData'),'Nest 网页采集器');try{if(!fs.existsSync(path.join(source,'manifest.json')))throw new Error('安装包中缺少网页采集扩展，请安装最新版本');await fs.promises.rm(target,{recursive:true,force:true});await fs.promises.cp(source,target,{recursive:true});const exe=choice.paths.find(p=>p&&fs.existsSync(p));if(!exe)return{ok:false,error:`没有检测到 ${choice.name}`,path:target};spawn(exe,[choice.url],{detached:true,stdio:'ignore'}).unref();clipboard.writeText(target);shell.showItemInFolder(path.join(target,'manifest.json'));return{ok:true,browser:choice.name,path:target}}catch(error){return{ok:false,error:error.message}}});
ipcMain.handle('library:update-asset', (_, id, changes) => {const data=readLibrary();if(!data)return null;const asset=data.assets.find(a=>a.id===id);if(!asset)return publicLibrary(data);try{const nextName=String(changes?.name??asset.name).trim()||asset.name;if(nextName!==asset.name)migrateAssetFilename(data,asset,nextName);Object.assign(asset,changes,{id:asset.id,file:asset.file,name:nextName,modifiedAt:Date.now()});writeJson(indexFile(libraryPath),data);return publicLibrary(data)}catch(error){return{error:`重命名文件失败：${error.message}`}}});
ipcMain.handle('library:batch-update', (_, ids, changes) => { const data = readLibrary(); if (!data) return null; if(changes?.folderId&& !data.folders.some(folder=>folder.id===changes.folderId))return{error:'目标文件夹不存在或已被删除'};const selected = new Set(Array.isArray(ids)?ids:[]); data.assets = data.assets.map(a => selected.has(a.id) ? { ...a, ...changes, id: a.id, file: a.file, tags: changes.addTag ? [...new Set([...(a.tags||[]), changes.addTag])] : (changes.tags||a.tags) } : a); if (changes.addTag) data.assets = data.assets.map(a => { const { addTag, ...rest } = a; return rest });syncPhysicalFolders(libraryPath,data); writeJson(indexFile(libraryPath), data); return publicLibrary(data); });
ipcMain.handle('library:batch-delete', async (_, ids) => {const data=readLibrary();if(!data)return null;const selected=new Set(ids),removed=new Set(),errors=[];for(const asset of data.assets.filter(a=>selected.has(a.id))){try{const target=storedAssetPath(asset.file);if(fs.existsSync(target))await shell.trashItem(target);removed.add(asset.id)}catch(error){errors.push(`${asset.name}: ${error.message}`)}}data.assets=data.assets.filter(a=>!removed.has(a.id));syncPhysicalFolders(libraryPath,data);data.lastDelete={removed:removed.size,errors,finishedAt:Date.now()};writeJson(indexFile(libraryPath),data);return publicLibrary(data)});
ipcMain.handle('library:delete-asset', async (_, id) => {const data=readLibrary();if(!data)return null;const asset=data.assets.find(a=>a.id===id);if(!asset)return publicLibrary(data);try{const target=storedAssetPath(asset.file);if(fs.existsSync(target))await shell.trashItem(target);data.assets=data.assets.filter(a=>a.id!==id);syncPhysicalFolders(libraryPath,data);writeJson(indexFile(libraryPath),data);return publicLibrary(data)}catch(error){return{error:`无法将“${asset.name}”移入回收站：${error.message}`}}});

const createWindow = () => { const win = new BrowserWindow({ width: 1440, height: 900, minWidth: 860, minHeight: 620, title: '小旺仔素材库', icon:path.join(app.getAppPath(),'build','icon.png'), backgroundColor: '#f7f6f2', autoHideMenuBar: process.platform!=='darwin', titleBarStyle: process.platform==='darwin'?'hiddenInset':'default', trafficLightPosition: process.platform==='darwin'?{x:14,y:15}:undefined, webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); win.loadFile(path.join(__dirname, '..', 'dist', 'index.html')); win.webContents.setWindowOpenHandler(({ url }) => { if (/^https?:/.test(url)) shell.openExternal(url); return { action: 'deny' }; }); };
app.whenReady().then(() => { if (!gotSingleInstanceLock) return; startClipServer(); protocol.handle('nest', request => {if(!libraryPath)return new Response('No library',{status:404});const parsed=new URL(request.url),file=path.basename(decodeURIComponent(parsed.pathname)),target=path.join(assetsDir(libraryPath),file);if(!fs.existsSync(target))return new Response('Not found',{status:404});const stat=fs.statSync(target),ext=path.extname(file).toLowerCase(),types={'.mp4':'video/mp4','.webm':'video/webm','.mov':'video/quicktime','.m4v':'video/mp4','.mp3':'audio/mpeg','.wav':'audio/wav','.flac':'audio/flac','.aac':'audio/aac','.m4a':'audio/mp4','.ogg':'audio/ogg','.opus':'audio/ogg','.wma':'audio/x-ms-wma','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.gif':'image/gif','.webp':'image/webp','.svg':'image/svg+xml','.bmp':'image/bmp','.avif':'image/avif'},type=types[ext]||'application/octet-stream',range=request.headers.get('range');if(range){const match=/bytes=(\d*)-(\d*)/.exec(range);if(!match)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${stat.size}`}});const start=match[1]?Number(match[1]):0,end=match[2]?Math.min(Number(match[2]),stat.size-1):stat.size-1;if(start>end||start>=stat.size)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${stat.size}`}});return new Response(Readable.toWeb(fs.createReadStream(target,{start,end})),{status:206,headers:{'Content-Type':type,'Accept-Ranges':'bytes','Content-Range':`bytes ${start}-${end}/${stat.size}`,'Content-Length':String(end-start+1)}})}return new Response(Readable.toWeb(fs.createReadStream(target)),{status:200,headers:{'Content-Type':type,'Accept-Ranges':'bytes','Content-Length':String(stat.size)}})}); createWindow(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); }); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
