import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Archive, Bell, Box, Briefcase, Brush, Bug, Camera, ChevronDown, ClipboardCopy, Copy, Download, Eye, FileText, Folder, FolderOpen, Grid2X2, Heart, Image as ImageIcon, Import, Info, LayoutGrid, List, Maximize2, Menu, MoreHorizontal, Music, Pencil, Plus, Puzzle, RotateCw, Search, SlidersHorizontal, Sparkles, Star, StickyNote, Tag, Trash2, Video, X } from 'lucide-react';
import './styles.css';

const DB_NAME = 'nest-assets';
const STORE = 'assets';
const seed = [
  { id:'seed-1', name:'Sea glass study', type:'image/svg+xml', size:18430, width:900, height:1200, tags:['灵感','摄影'], favorite:true, createdAt:Date.now()-5000, url:'./samples/sea.svg' },
  { id:'seed-2', name:'Soft architecture', type:'image/svg+xml', size:21800, width:1200, height:820, tags:['建筑','留白'], createdAt:Date.now()-4000, url:'./samples/arch.svg' },
  { id:'seed-3', name:'Orange chair', type:'image/svg+xml', size:9200, width:900, height:1120, tags:['家具','配色'], createdAt:Date.now()-3000, url:'./samples/chair.svg' },
  { id:'seed-4', name:'Editorial objects', type:'image/svg+xml', size:11000, width:1200, height:800, tags:['静物','编辑'], createdAt:Date.now()-2000, url:'./samples/objects.svg' },
  { id:'seed-5', name:'Quiet landscape', type:'image/svg+xml', size:24400, width:1200, height:900, tags:['自然','摄影'], createdAt:Date.now()-1000, url:'./samples/landscape.svg' },
];

function openDB(){ return new Promise((resolve,reject)=>{ const req=indexedDB.open(DB_NAME,1); req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'}); req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); }); }
async function getAssets(){ const db=await openDB(); return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}); }
async function saveAsset(asset){ const db=await openDB(); return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(asset);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)}); }
async function removeAsset(id){ const db=await openDB(); return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)}); }
const PENDING_KEY='nest-pending-edits';
const INTERNAL_DRAG='application/x-nest-asset-ids';
const FOLDER_DRAG='application/x-nest-folder-id';
const ROOT_FOLDER_DROP='__folder_root__';
const SIDEBAR_WIDTH_KEY='nest-sidebar-width';
const VIEW_MODE_KEY='nest-view-mode';
const THEME_COLOR_KEY='nest-theme-color';
const VIEW_MODES=['standard','compact','list'];
const THEME_COLORS=['#267ff4','#45c28b','#8267ec','#f35f64','#ff9f2f','#44b9d8','#dc7fbd'];
const clampSidebarWidth=value=>Math.min(440,Math.max(190,Number(value)||232));
function readPending(){try{return JSON.parse(localStorage.getItem(PENDING_KEY)||'{}')}catch{return {}}}
function writePending(id,data){const all=readPending();all[id]={...(all[id]||{}),...data};localStorage.setItem(PENDING_KEY,JSON.stringify(all))}
function clearPending(id){const all=readPending();delete all[id];if(Object.keys(all).length)localStorage.setItem(PENDING_KEY,JSON.stringify(all));else localStorage.removeItem(PENDING_KEY)}
const fmt=n=>n>1e6?`${(n/1e6).toFixed(1)} MB`:n<1000?'< 1 KB':`${Math.round(n/1000)} KB`;
const FOLDER_ICONS=[['folder',Folder],['tag',Tag],['image',ImageIcon],['video',Video],['file',FileText],['star',Star],['heart',Heart],['briefcase',Briefcase],['camera',Camera],['music',Music],['box',Box],['brush',Brush],['bell',Bell]];
const FOLDER_COLORS=['#f35f64','#ff9f2f','#f6c744','#45c28b','#44b9d8','#438df5','#8267ec','#dc7fbd','#8f98a3'];
const folderIcon=key=>FOLDER_ICONS.find(([name])=>name===key)?.[1]||Folder;
if(window.nestDesktop?.platform)document.documentElement.dataset.platform=window.nestDesktop.platform;

function App(){
  const [assets,setAssets]=useState([]), [selected,setSelected]=useState(null), [query,setQuery]=useState(''), [currentTag,setCurrentTag]=useState(null), [filter,setFilter]=useState('全部素材'), [drag,setDrag]=useState(false), [ready,setReady]=useState(false);
  const [library,setLibrary]=useState(null), [activeFolder,setActiveFolder]=useState(null), [collapsedFolders,setCollapsedFolders]=useState(()=>new Set()), [sidebarWidth,setSidebarWidth]=useState(()=>clampSidebarWidth(localStorage.getItem(SIDEBAR_WIDTH_KEY))), [sortOrder,setSortOrder]=useState('recent'), [message,setMessage]=useState(''), [viewMode,setViewMode]=useState(()=>VIEW_MODES.includes(localStorage.getItem(VIEW_MODE_KEY))?localStorage.getItem(VIEW_MODE_KEY):'standard'), [selectedIds,setSelectedIds]=useState([]), [marquee,setMarquee]=useState(null), [dropFolderId,setDropFolderId]=useState(undefined), [importing,setImporting]=useState(false), [previewId,setPreviewId]=useState(null), [zoom,setZoom]=useState(1), [rotation,setRotation]=useState(0), [checker,setChecker]=useState(false), [visibleLimit,setVisibleLimit]=useState(160);
  const [dialogState,setDialogState]=useState(null),[themePanel,setThemePanel]=useState(false),[themeColor,setThemeColor]=useState(()=>localStorage.getItem(THEME_COLOR_KEY)||'#267ff4');
  const [contextMenu,setContextMenu]=useState(null);
  const [extensionPanel,setExtensionPanel]=useState(false),[extensionResult,setExtensionResult]=useState(null),[extensionBusy,setExtensionBusy]=useState(false);
  const [updateInfo,setUpdateInfo]=useState(null),[updatePanel,setUpdatePanel]=useState(false),[updateChecking,setUpdateChecking]=useState(false);
  const [updateProgress,setUpdateProgress]=useState(null),[updateFile,setUpdateFile]=useState(''),[updateError,setUpdateError]=useState('');
  const desktop=Boolean(window.nestDesktop);
  const recycleBinName=window.nestDesktop?.platform==='darwin'?'废纸篓':'回收站';
  const input=useRef(), assetsRef=useRef([]), saveTimers=useRef(new Map()), pendingSaves=useRef(new Map()), desktopTimers=useRef(new Map()), desktopChanges=useRef(new Map()), marqueeStart=useRef(null), marqueeBase=useRef(new Set()), lastSelectedId=useRef(null), sidebarResizing=useRef(false), externalDragActive=useRef(false), externalDragTimer=useRef(null);
  const askText=(title,defaultValue='',placeholder='')=>new Promise(resolve=>setDialogState({kind:'prompt',title,defaultValue,placeholder,resolve}));
  const askConfirm=(title,detail='')=>new Promise(resolve=>setDialogState({kind:'confirm',title,detail,resolve}));
  const askFolder=(folders,parentId=null)=>new Promise(resolve=>setDialogState({kind:'folder',title:'新建文件夹',folders,parentId,resolve}));
  const resolveDialog=value=>{dialogState?.resolve(value);setDialogState(null)};
  useEffect(()=>{if(desktop){window.nestDesktop.currentLibrary().then(lib=>{if(lib){setLibrary(lib);assetsRef.current=lib.assets;setAssets(lib.assets)}}).catch(error=>setMessage(`打开资源库失败：${error.message}`)).finally(()=>setReady(true));const unsubscribeLibrary=window.nestDesktop.onLibraryChanged?.(lib=>{if(lib){setLibrary(lib);assetsRef.current=lib.assets;setAssets(lib.assets);setMessage('网页采集的新素材已加入');setTimeout(()=>setMessage(''),3500)}});const unsubscribeDrag=window.nestDesktop.onExternalDragError?.(error=>{setMessage(`无法拖出素材：${error}`);setTimeout(()=>setMessage(''),5000)});return()=>{unsubscribeLibrary?.();unsubscribeDrag?.()}}getAssets().then(a=>{const pending=readPending();const loaded=(a.length?a:seed).map(asset=>pending[asset.id]?{...asset,...pending[asset.id]}:asset);assetsRef.current=loaded;setAssets(loaded);setReady(true);for(const asset of loaded){if(pending[asset.id])saveAsset({...asset,url:''}).then(()=>clearPending(asset.id))}})},[]);
  useEffect(()=>{if(!desktop)return;const timer=setTimeout(()=>window.nestDesktop.checkUpdate().then(result=>{if(result?.ok){setUpdateInfo(result);if(result.available)setUpdatePanel(true)}}),1800);return()=>clearTimeout(timer)},[desktop]);
  useEffect(()=>desktop?window.nestDesktop.onUpdateProgress?.(setUpdateProgress):undefined,[desktop]);
  const checkUpdate=async()=>{setUpdateChecking(true);const result=await window.nestDesktop.checkUpdate();setUpdateChecking(false);if(result?.error){setMessage(result.error);setTimeout(()=>setMessage(''),4000);return}setUpdateInfo(result);setUpdatePanel(true)};
  const downloadUpdate=async()=>{setUpdateError('');setUpdateFile('');setUpdateProgress({percent:0,received:0,total:0});const result=await window.nestDesktop.downloadUpdate({url:updateInfo.downloadUrl,name:updateInfo.downloadName});if(result?.error){setUpdateError(result.error);setUpdateProgress(null);return}setUpdateFile(result.filePath);setUpdateProgress(current=>({...current,percent:100}))};
  const flushSaves=()=>{for(const [id,asset] of pendingSaves.current){clearTimeout(saveTimers.current.get(id));saveAsset({...asset,url:''}).then(()=>clearPending(id))}pendingSaves.current.clear();saveTimers.current.clear();if(desktop){for(const [id,changes] of desktopChanges.current){clearTimeout(desktopTimers.current.get(id));window.nestDesktop.updateAsset(id,changes)}desktopChanges.current.clear();desktopTimers.current.clear()}};
  useEffect(()=>{const onPageHide=()=>flushSaves();const onVisibility=()=>{if(document.visibilityState==='hidden')flushSaves()};window.addEventListener('pagehide',onPageHide);document.addEventListener('visibilitychange',onVisibility);return()=>{flushSaves();window.removeEventListener('pagehide',onPageHide);document.removeEventListener('visibilitychange',onVisibility)}},[]);
  useEffect(()=>{const onKey=e=>{if(e.key==='Escape'){flushSaves();setPreviewId(null);setSelected(null);setSelectedIds([]);setMarquee(null);marqueeStart.current=null;setContextMenu(null);setExtensionPanel(false)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
  useEffect(()=>{if(!contextMenu)return;const close=()=>setContextMenu(null);window.addEventListener('click',close);window.addEventListener('blur',close);return()=>{window.removeEventListener('click',close);window.removeEventListener('blur',close)}},[contextMenu]);
  const activeFolderIds=useMemo(()=>{if(!activeFolder)return null;const ids=new Set([activeFolder]),folders=library?.folders||[];for(let changed=true;changed;){changed=false;for(const folder of folders)if(folder.parentId&&ids.has(folder.parentId)&&!ids.has(folder.id)){ids.add(folder.id);changed=true}}return ids},[library,activeFolder]);
  const shown=useMemo(()=>assets.filter(a=>{ const q=query.toLowerCase(); const match=!q||a.name.toLowerCase().includes(q)||(a.tags||[]).some(t=>t.toLowerCase().includes(q)); const tagMatch=!currentTag||(a.tags||[]).includes(currentTag); const f=filter==='全部素材'||(filter==='收藏夹'&&a.favorite)||(filter==='图片'&&a.type.startsWith('image'))||(filter==='视频'&&a.type.startsWith('video'))||(filter==='音频'&&a.type.startsWith('audio'))||(filter==='未分类'&&!a.folderId)||(filter==='最近'&&Date.now()-a.createdAt<7*86400000); return match&&tagMatch&&f&&(!activeFolderIds||activeFolderIds.has(a.folderId)) }).sort((a,b)=>sortOrder==='name'?a.name.localeCompare(b.name,'zh-CN'):b.createdAt-a.createdAt),[assets,query,currentTag,filter,activeFolderIds,sortOrder]);
  const displayed=shown.slice(0,visibleLimit);
  const allShownSelected=shown.length>0&&shown.every(asset=>selectedIds.includes(asset.id));
  const toggleSelectAll=()=>{const shownIds=new Set(shown.map(asset=>asset.id));setSelectedIds(ids=>allShownSelected?ids.filter(id=>!shownIds.has(id)):[...new Set([...ids,...shownIds])]);setSelected(null)};
  useEffect(()=>{if(selected&&!shown.some(a=>a.id===selected.id))setSelected(null)},[shown,selected]);
  useEffect(()=>setVisibleLimit(160),[query,currentTag,filter,activeFolder,sortOrder]);
  const orderedFolders=useMemo(()=>{const all=library?.folders||[],out=[];const walk=(parentId=null,depth=0)=>all.filter(f=>(f.parentId||null)===parentId).forEach(f=>{const hasChildren=all.some(child=>child.parentId===f.id);out.push({...f,depth,hasChildren});if(!collapsedFolders.has(f.id))walk(f.id,depth+1)});walk();return out},[library,collapsedFolders]);
  const currentFolder=activeFolder?(library?.folders||[]).find(folder=>folder.id===activeFolder):null;
  const contentFolders=useMemo(()=>filter==='全部素材'&&!query&&!currentTag?(library?.folders||[]).filter(folder=>(folder.parentId||null)===(activeFolder||null)):[],[library,filter,query,currentTag,activeFolder]);
  const folderAssetCounts=useMemo(()=>{const folders=library?.folders||[],byId=new Map(folders.map(folder=>[folder.id,folder])),counts=new Map(folders.map(folder=>[folder.id,0]));for(const asset of assets){let id=asset.folderId;const visited=new Set();while(id&&byId.has(id)&&!visited.has(id)){visited.add(id);counts.set(id,(counts.get(id)||0)+1);id=byId.get(id).parentId}}return counts},[library,assets]);
  const openFolder=folder=>{setFilter('全部素材');setQuery('');setCurrentTag(null);setActiveFolder(folder.id);setSelected(null);setSelectedIds([])};
  const applyLibrary=(lib,{reset=false}={})=>{if(!lib||lib.error){if(lib?.error)setMessage(lib.error);return}setMessage('');setLibrary(lib);assetsRef.current=lib.assets;setAssets(lib.assets);if(reset){setActiveFolder(null);setSelected(null)}else setSelected(current=>current?lib.assets.find(a=>a.id===current.id)||null:null)};
  const createLibrary=async()=>applyLibrary(await window.nestDesktop.createLibrary(),{reset:true});
  const openLibrary=async()=>applyLibrary(await window.nestDesktop.openLibrary(),{reset:true});
  const showLibraryInfo=async()=>{if(!library){setMessage('Nest 本地素材库');return}const health=await window.nestDesktop.health();if(!health)return;const text=`路径：${library.path}\n素材：${health.total} 个\n缺失文件：${health.missing.length}\n每日备份：${health.backupDir}`;if(health.missing.length){if(await askConfirm('发现缺失文件',`${text}\n\n是否备份索引并移除缺失记录？`))applyLibrary(await window.nestDesktop.repair())}else await askConfirm('资源库状态正常',text)};
  const prepareExtension=async browser=>{setExtensionBusy(true);setExtensionResult(null);try{setExtensionResult(await window.nestDesktop.prepareExtension(browser))}catch(error){setExtensionResult({ok:false,error:error.message})}finally{setExtensionBusy(false)}};
  const showImportResult=lib=>{applyLibrary(lib);if(lib?.lastImport){const r=lib.lastImport;setMessage(r.errors.length&&!r.imported?r.errors[0]:`已导入 ${r.imported} 个，跳过重复 ${r.duplicates} 个${r.errors.length?`，失败 ${r.errors.length} 个`:''}`);setTimeout(()=>setMessage(''),5000)}};
  const nativeImport=async()=>{setImporting(true);try{showImportResult(await window.nestDesktop.importAssets(activeFolder))}finally{setImporting(false)}};
  const droppedImport=async files=>{setImporting(true);try{showImportResult(await window.nestDesktop.importDropped([...files],activeFolder))}finally{setImporting(false);setDrag(false)}};
  const droppedWebImage=async transfer=>{const files=[...transfer.files];if(files.length)return droppedImport(files);const html=transfer.getData('text/html');let url=html?new DOMParser().parseFromString(html,'text/html').querySelector('img')?.src||'':'';if(!url)url=transfer.getData('text/uri-list').split(/\r?\n/).find(x=>x&&!x.startsWith('#'))||'';if(!url)url=transfer.getData('text/plain').trim();if(/^https?:\/\//i.test(url)){setImporting(true);try{showImportResult(await window.nestDesktop.importUrl(url,activeFolder))}finally{setImporting(false);setDrag(false)}return}setDrag(false);setMessage('没有识别到图片文件或图片网址，可使用 Nest 网页采集扩展右键保存');setTimeout(()=>setMessage(''),4500)};
  const addFolderAt=async(parentId=activeFolder)=>{const options=await askFolder(orderedFolders,parentId);if(!options?.name?.trim())return;try{const lib=await window.nestDesktop.addFolder(options);applyLibrary(lib);if(!lib?.error){setFilter('全部素材');setQuery('');setCurrentTag(null);setActiveFolder(options.parentId||null);if(options.parentId)setCollapsedFolders(current=>{const next=new Set(current);next.delete(options.parentId);return next});setMessage(`文件夹“${options.name.trim()}”已创建`);setTimeout(()=>setMessage(''),2500)}}catch(error){setMessage(`新建文件夹失败：${error.message}`);setTimeout(()=>setMessage(''),5000)}};
  const addFolder=()=>addFolderAt(activeFolder);
  const addLibraryTag=async()=>{const name=await askText('新建标签','','输入标签名称');if(!name?.trim())return;try{applyLibrary(await window.nestDesktop.addTag(name.trim()))}catch(error){setMessage(`新建标签失败：${error.message}`);setTimeout(()=>setMessage(''),5000)}};
  const deleteLibraryTag=async name=>{if(await askConfirm(`删除标签“${name}”？`,'该标签也会从所有素材中移除。')){applyLibrary(await window.nestDesktop.deleteTag(name));if(currentTag===name)setCurrentTag(null)}};
  const renameFolder=async folder=>{const name=await askText('重命名文件夹',folder.name,'输入新名称');if(name?.trim())applyLibrary(await window.nestDesktop.updateFolder(folder.id,{name:name.trim()}))};
  const deleteFolder=async folder=>{const count=folderAssetCounts.get(folder.id)||0;if(await askConfirm(`删除文件夹“${folder.name}”及全部内容？`,`将递归删除所有子文件夹和其中 ${count} 个素材，原始文件会移入${recycleBinName}。`)){const lib=await window.nestDesktop.deleteFolder(folder.id);applyLibrary(lib);if(lib?.lastDelete?.completed){if(activeFolder&&!lib.folders.some(item=>item.id===activeFolder))setActiveFolder(null);setSelectedIds([]);setMessage(`已删除 ${lib.lastDelete.removedFolders} 个文件夹和 ${lib.lastDelete.removedAssets} 个素材`)}else if(lib?.lastDelete?.errors?.length)setMessage(`${lib.lastDelete.errors.length} 个文件无法移入${recycleBinName}，相关文件夹已保留`);setTimeout(()=>setMessage(''),5000)}};
  const toggleSelected=id=>setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
  const batchUpdate=async changes=>{flushSaves();applyLibrary(await window.nestDesktop.batchUpdate(selectedIds,changes));setSelectedIds([])};
  const batchTag=async()=>{const tag=await askText('批量添加标签','','输入标签名称');if(tag?.trim())batchUpdate({addTag:tag.trim()})};
  const batchMove=async()=>{const choices=orderedFolders.map((f,i)=>`${i+1}. ${'—'.repeat(f.depth)}${f.name}`).join('\n');const value=await askText('移动所选素材','',`输入 0 移到未分类，或输入文件夹编号\n${choices}`);if(value!==null){const folder=orderedFolders[Number(value)-1];if(value==='0'||folder)batchUpdate({folderId:folder?.id||null});else if(value!=='')setMessage('文件夹编号无效')}};
  const batchDelete=async()=>{if(await askConfirm(`删除所选的 ${selectedIds.length} 个素材？`,`原文件会移到${recycleBinName}。`)){flushSaves();const lib=await window.nestDesktop.batchDelete(selectedIds);applyLibrary(lib);setSelectedIds([]);if(lib?.lastDelete?.errors?.length){setMessage(`有 ${lib.lastDelete.errors.length} 个文件无法移入${recycleBinName}，记录已保留`);setTimeout(()=>setMessage(''),5000)}}};
  const contextRename=async asset=>{const name=await askText('重命名素材',asset.name,'输入素材名称');if(name?.trim())patch(asset.id,{name:name.trim()})};
  const contextTag=async asset=>{const tag=await askText('添加标签','','输入标签名称');if(tag?.trim())patch(asset.id,{tags:[...new Set([...(asset.tags||[]),tag.trim()])]})};
  const contextNote=async asset=>{const note=await askText('添加注释',asset.note||'','输入素材注释');if(note!==null)patch(asset.id,{note})};
  const contextMove=async(asset,folderId)=>applyLibrary(await window.nestDesktop.batchUpdate([asset.id],{folderId}));
  const copyAssetToClipboard=async asset=>{if(!desktop||!asset)return;const result=await window.nestDesktop.copyAsset(asset.id);setMessage(result?.error?result.error:'文件已复制，可粘贴到其他位置');setTimeout(()=>setMessage(''),2500)};
  const startAssetDrag=(event,asset)=>{if(event.target.closest('button,input')){event.preventDefault();return}const ids=selectedIds.includes(asset.id)?selectedIds:[asset.id],isAudio=asset.type?.startsWith('audio');if(isAudio||event.target.closest('.thumb')){event.preventDefault();event.stopPropagation();externalDragActive.current=true;clearTimeout(externalDragTimer.current);externalDragTimer.current=setTimeout(()=>{externalDragActive.current=false},30000);window.nestDesktop?.startExternalDrag(ids);return}event.dataTransfer.effectAllowed='move';event.dataTransfer.setData(INTERNAL_DRAG,JSON.stringify(ids));event.dataTransfer.setData('text/plain',asset.name)};
  const dropAssets=async(event,folderId)=>{const raw=event.dataTransfer.getData(INTERNAL_DRAG);if(!raw)return false;event.preventDefault();event.stopPropagation();let ids=[];try{ids=JSON.parse(raw)}catch{}if(!Array.isArray(ids)||!ids.length)return false;flushSaves();applyLibrary(await window.nestDesktop.batchUpdate(ids,{folderId}));setSelectedIds([]);setDropFolderId(undefined);setDrag(false);setMessage(folderId?'素材已移动到文件夹':'素材已移动到未分类');setTimeout(()=>setMessage(''),2500);return true};
  const toggleFolderCollapsed=id=>setCollapsedFolders(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
  const startFolderDrag=(event,folder)=>{event.stopPropagation();event.dataTransfer.effectAllowed='move';event.dataTransfer.setData(FOLDER_DRAG,folder.id);event.dataTransfer.setData('text/plain',folder.name)};
  const dropMovedFolder=async(event,parentId)=>{const id=event.dataTransfer.getData(FOLDER_DRAG);if(!id)return false;event.preventDefault();event.stopPropagation();if(id===parentId){setDropFolderId(undefined);return false}const result=await window.nestDesktop.updateFolder(id,{parentId});applyLibrary(result);if(!result?.error){if(parentId)setCollapsedFolders(current=>{const next=new Set(current);next.delete(parentId);return next});setMessage(parentId?'文件夹已移动到新父级':'文件夹已移动到根目录');setTimeout(()=>setMessage(''),2500)}setDropFolderId(undefined);setDrag(false);return true};
  const contextDelete=async asset=>{if(await askConfirm(`删除“${asset.name}”？`,`原文件会移到${recycleBinName}。`))del(asset.id)};
  const revealAsset=async id=>{const result=await window.nestDesktop.revealAsset(id,true);if(result?.error){setMessage(result.error);setTimeout(()=>setMessage(''),5000)}else if(result?.library)applyLibrary(result.library)};
  const openAssetAction=async id=>{const result=await window.nestDesktop.openAsset(id);if(result?.error){setMessage(result.error);setTimeout(()=>setMessage(''),5000)}};
  const exportAssetAction=async id=>{const result=await window.nestDesktop.exportAsset(id);if(result?.error)setMessage(result.error);else if(result?.ok)setMessage('素材已导出');if(!result?.canceled)setTimeout(()=>setMessage(''),3500)};
  const duplicateAssetAction=async id=>{const result=await window.nestDesktop.duplicateAsset(id);applyLibrary(result);if(!result?.error){setMessage('素材已复制');setTimeout(()=>setMessage(''),2500)}};
  const previewIndex=shown.findIndex(a=>a.id===previewId), previewAsset=shown[previewIndex];
  const resetPreviewView=()=>{setZoom(1);setRotation(0)};
  const movePreview=delta=>{if(!shown.length)return;setPreviewId(shown[(previewIndex+delta+shown.length)%shown.length].id);resetPreviewView()};
  const clickAsset=(event,asset)=>{if(event.shiftKey&&lastSelectedId.current){const from=shown.findIndex(item=>item.id===lastSelectedId.current),to=shown.findIndex(item=>item.id===asset.id);if(from>=0&&to>=0){const range=shown.slice(Math.min(from,to),Math.max(from,to)+1).map(item=>item.id);setSelectedIds(ids=>event.ctrlKey||event.metaKey?[...new Set([...ids,...range])]:range);setSelected(asset);return}}if(event.ctrlKey||event.metaKey){setSelectedIds(ids=>ids.includes(asset.id)?ids.filter(id=>id!==asset.id):[...ids,asset.id]);setSelected(asset)}else{setSelectedIds([]);setSelected(asset)}lastSelectedId.current=asset.id};
  const beginMarquee=event=>{if(event.button!==0||event.target.closest('article,button,input,select,textarea'))return;event.currentTarget.setPointerCapture(event.pointerId);marqueeStart.current={x:event.clientX,y:event.clientY,moved:false};marqueeBase.current=new Set(event.ctrlKey||event.metaKey?selectedIds:[]);setMarquee({left:event.clientX,top:event.clientY,width:0,height:0})};
  const moveMarquee=event=>{const start=marqueeStart.current;if(!start)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.abs(dx)>3||Math.abs(dy)>3)start.moved=true;const box={left:Math.min(start.x,event.clientX),top:Math.min(start.y,event.clientY),right:Math.max(start.x,event.clientX),bottom:Math.max(start.y,event.clientY)};setMarquee({left:box.left,top:box.top,width:box.right-box.left,height:box.bottom-box.top});if(!start.moved)return;const ids=new Set(marqueeBase.current);document.querySelectorAll('article[data-asset-id]').forEach(element=>{const rect=element.getBoundingClientRect();if(rect.right>=box.left&&rect.left<=box.right&&rect.bottom>=box.top&&rect.top<=box.bottom)ids.add(element.dataset.assetId)});setSelectedIds([...ids]);setSelected(null)};
  const endMarquee=event=>{const start=marqueeStart.current;if(!start)return;if(!start.moved){setSelectedIds([]);setSelected(null)}if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);marqueeStart.current=null;setMarquee(null)};
  const beginSidebarResize=event=>{if(event.button!==0)return;event.preventDefault();sidebarResizing.current=true;event.currentTarget.setPointerCapture(event.pointerId);document.body.classList.add('resizing-sidebar')};
  const moveSidebarResize=event=>{if(sidebarResizing.current)setSidebarWidth(clampSidebarWidth(event.clientX))};
  const endSidebarResize=event=>{if(!sidebarResizing.current)return;sidebarResizing.current=false;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);document.body.classList.remove('resizing-sidebar');const width=clampSidebarWidth(event.clientX);setSidebarWidth(width);localStorage.setItem(SIDEBAR_WIDTH_KEY,String(width))};
  const resetSidebarWidth=()=>{setSidebarWidth(232);localStorage.setItem(SIDEBAR_WIDTH_KEY,'232')};
  const cycleViewMode=()=>setViewMode(current=>{const next=VIEW_MODES[(VIEW_MODES.indexOf(current)+1)%VIEW_MODES.length];localStorage.setItem(VIEW_MODE_KEY,next);return next});
  const importFiles=async files=>{ for(const file of [...files].filter(f=>/^(image|video|audio)\//.test(f.type))){ const tempUrl=URL.createObjectURL(file);const dims=file.type.startsWith('image/')?await new Promise(res=>{const im=new Image();im.onload=()=>res([im.naturalWidth,im.naturalHeight]);im.onerror=()=>res([0,0]);im.src=tempUrl}):[0,0];const a={id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),type:file.type,size:file.size,width:dims[0],height:dims[1],tags:[],favorite:false,createdAt:Date.now(),blob:file,url:tempUrl};await saveAsset({...a,url:''});assetsRef.current=[a,...assetsRef.current];setAssets(assetsRef.current); }};
  const patch=(id,data)=>{const target=assetsRef.current.find(a=>a.id===id);if(!target)return;const updated={...target,...data};assetsRef.current=assetsRef.current.map(a=>a.id===id?updated:a);setAssets(assetsRef.current);setSelected(s=>s?.id===id?updated:s);if(desktop){desktopChanges.current.set(id,{...(desktopChanges.current.get(id)||{}),...data});clearTimeout(desktopTimers.current.get(id));desktopTimers.current.set(id,setTimeout(async()=>{const changes=desktopChanges.current.get(id);desktopChanges.current.delete(id);desktopTimers.current.delete(id);if(!changes)return;try{const result=await window.nestDesktop.updateAsset(id,changes);if(result?.error){setMessage(result.error);setTimeout(()=>setMessage(''),5000);const current=await window.nestDesktop.currentLibrary();applyLibrary(current);return}applyLibrary(result)}catch(error){setMessage(`保存失败：${error.message}`);setTimeout(()=>setMessage(''),5000)}},300));return}writePending(id,data);pendingSaves.current.set(id,updated);clearTimeout(saveTimers.current.get(id));saveTimers.current.set(id,setTimeout(()=>{const pending=pendingSaves.current.get(id);if(pending)saveAsset({...pending,url:''}).then(()=>clearPending(id));pendingSaves.current.delete(id);saveTimers.current.delete(id)},250))};
  const del=async id=>{if(desktop){clearTimeout(desktopTimers.current.get(id));desktopTimers.current.delete(id);desktopChanges.current.delete(id);applyLibrary(await window.nestDesktop.deleteAsset(id));return}clearTimeout(saveTimers.current.get(id));await removeAsset(id);assetsRef.current=assetsRef.current.filter(a=>a.id!==id);setAssets(assetsRef.current);setSelected(null)};
  useEffect(()=>{const onShortcut=event=>{if(event.target.closest('input,textarea,select'))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'){event.preventDefault();toggleSelectAll()}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='c'){const asset=selected||assetsRef.current.find(item=>selectedIds.includes(item.id));if(asset){event.preventDefault();copyAssetToClipboard(asset)}}if(previewId&&event.key==='ArrowLeft')movePreview(-1);if(previewId&&event.key==='ArrowRight')movePreview(1);if(previewId&&event.key.toLowerCase()==='r')setRotation(value=>(value+90)%360);if(previewId&&event.key==='0')resetPreviewView()};window.addEventListener('keydown',onShortcut);return()=>window.removeEventListener('keydown',onShortcut)},[shown,selectedIds,selected,previewId]);
  useEffect(()=>{if(!ready)return;const hydrated=assetsRef.current.map(a=>a.blob&&!a.url?{...a,url:URL.createObjectURL(a.blob)}:a);assetsRef.current=hydrated;setAssets(hydrated)},[ready]);
  const nav=[['全部素材',LayoutGrid],['未分类',Archive],['收藏夹',Heart],['最近',Sparkles],['图片',ImageIcon],['视频',Video],['音频',Music]];
  return <div className={`app ${selected?'detail-open':''}`} style={{'--sidebar-width':`${sidebarWidth}px`,'--accent':themeColor}} onDragOver={e=>{e.preventDefault();if(externalDragActive.current)return;if(e.dataTransfer.types.includes(INTERNAL_DRAG)||e.dataTransfer.types.includes(FOLDER_DRAG)){e.dataTransfer.dropEffect='move';return}setDrag(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget)){setDrag(false);setDropFolderId(undefined)}}} onDrop={e=>{e.preventDefault();if(externalDragActive.current){externalDragActive.current=false;clearTimeout(externalDragTimer.current);setDrag(false);return}if(e.dataTransfer.types.includes(INTERNAL_DRAG)||e.dataTransfer.types.includes(FOLDER_DRAG)){setDrag(false);setDropFolderId(undefined);return}desktop?droppedWebImage(e.dataTransfer):(setDrag(false),importFiles(e.dataTransfer.files))}}>
    <aside><div className="brand"><div className="mark">N</div><span>{library?.name||'Nest'}</span><button aria-label="打开其他资源库" title="打开其他资源库" onClick={desktop?openLibrary:undefined}><Menu size={19}/></button></div><button className="import" onClick={desktop?nativeImport:()=>input.current.click()}><Plus size={18}/> 导入素材</button>{desktop&&library&&<button className="new-folder-primary" onClick={addFolder}><Folder size={17}/> 新建文件夹</button>}<input ref={input} hidden multiple type="file" accept="image/*,video/*,audio/*" onChange={e=>importFiles(e.target.files)}/>
      <nav>{nav.map(([n,I])=><button className={`${filter===n&&!activeFolder&&!currentTag?'active':''} ${n==='未分类'&&dropFolderId===null?'drop-target':''}`} onDragOver={n==='未分类'?e=>{if(e.dataTransfer.types.includes(INTERNAL_DRAG)){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';setDropFolderId(null)}}:undefined} onDragLeave={n==='未分类'?()=>setDropFolderId(undefined):undefined} onDrop={n==='未分类'?e=>dropAssets(e,null):undefined} onClick={()=>{setFilter(n);setCurrentTag(null);if(n==='全部素材')setQuery('');setActiveFolder(null);setSelected(null);setSelectedIds([])}} key={n}><I size={17}/><span>{n}</span>{n==='全部素材'&&<b>{assets.length}</b>}</button>)}</nav>
      <div className={`nav-title folder-root-drop ${dropFolderId===ROOT_FOLDER_DROP?'drop-target':''}`} onDragOver={e=>{if(e.dataTransfer.types.includes(FOLDER_DRAG)){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';setDropFolderId(ROOT_FOLDER_DROP)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDropFolderId(undefined)}} onDrop={e=>dropMovedFolder(e,null)}><span>文件夹</span><button aria-label="新建文件夹" title={activeFolder?'在当前文件夹中新建子文件夹':'新建文件夹'} onClick={desktop?addFolder:undefined}><Plus size={15}/></button></div><nav>{desktop?orderedFolders.map(f=><div draggable className={`folder-row ${activeFolder===f.id?'active':''} ${dropFolderId===f.id?'drop-target':''}`} style={{paddingLeft:4+f.depth*14}} key={f.id} onDragStart={e=>startFolderDrag(e,f)} onDragEnd={()=>setDropFolderId(undefined)} onDragOver={e=>{if(e.dataTransfer.types.includes(INTERNAL_DRAG)||e.dataTransfer.types.includes(FOLDER_DRAG)){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';setDropFolderId(f.id)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDropFolderId(undefined)}} onDrop={e=>e.dataTransfer.types.includes(FOLDER_DRAG)?dropMovedFolder(e,f.id):dropAssets(e,f.id)} onContextMenu={e=>{e.preventDefault();e.stopPropagation();setContextMenu({kind:'folder',x:e.clientX,y:e.clientY,folder:f})}}><button className={`folder-toggle ${collapsedFolders.has(f.id)?'collapsed':''}`} aria-label={collapsedFolders.has(f.id)?`展开 ${f.name}`:`收起 ${f.name}`} disabled={!f.hasChildren} onClick={e=>{e.stopPropagation();if(f.hasChildren)toggleFolderCollapsed(f.id)}}><ChevronDown size={13}/></button><button className="folder-main" onClick={()=>openFolder(f)}><FolderMark folder={f}/><span>{f.name}</span><b>{folderAssetCounts.get(f.id)||0}</b></button><button className="folder-action" title="重命名" onClick={()=>renameFolder(f)}><MoreHorizontal size={14}/></button><button className="folder-action danger" title="删除文件夹" onClick={()=>deleteFolder(f)}><X size={13}/></button></div>):<><button><Folder size={17}/><span>灵感收集</span><b>{assets.filter(a=>a.tags.includes('灵感')).length}</b></button><button><Folder size={17}/><span>品牌项目</span></button></>}</nav>
      <div className="nav-title"><span>标签</span><button aria-label="新建标签" title="新建标签" onClick={desktop?addLibraryTag:undefined}><Plus size={15}/></button></div><div className="tag-list">{[...new Set([...(library?.tags||[]),...assets.flatMap(a=>a.tags||[])])].map((t,i)=><div className="tag-entry" key={t}><button className={`tag-filter ${currentTag===t?'active':''}`} onClick={()=>{setCurrentTag(current=>current===t?null:t);setFilter('全部素材');setActiveFolder(null);setSelected(null);setSelectedIds([])}}><i className={`dot c${i%4}`}/>{t}</button>{desktop&&<button className="tag-remove" aria-label={`删除标签 ${t}`} title="删除标签" onClick={()=>deleteLibraryTag(t)}><X size={12}/></button>}</div>)}</div>
      <button className="storage" title={library?'点击切换到其他资源库':'打开资源库'} onClick={desktop?openLibrary:undefined}><Sparkles size={16}/><div><strong>{library?'资源库已连接 · 点击切换':'本地素材库'}</strong><span>{library?.path||'你的素材仅保存在此设备'}</span></div><ChevronDown size={14}/></button>
    </aside>
    <div className="sidebar-resizer" role="separator" aria-label="调整左侧栏宽度" aria-orientation="vertical" title="拖动调整左侧栏宽度，双击恢复默认" onPointerDown={beginSidebarResize} onPointerMove={moveSidebarResize} onPointerUp={endSidebarResize} onPointerCancel={endSidebarResize} onDoubleClick={resetSidebarWidth}/>
    <main className={`view-${viewMode}`} onScroll={e=>{const el=e.currentTarget;if(el.scrollHeight-el.scrollTop-el.clientHeight<900&&visibleLimit<shown.length)setVisibleLimit(x=>x+160)}}><header><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称、标签…"/>{query&&<button className="search-clear" aria-label="清除搜索" title="清除搜索" onClick={()=>setQuery('')}><X size={16}/></button>}</div><button className={`icon-btn update-button ${updateInfo?.available?'has-update':''}`} title={updateInfo?.available?`发现新版本 ${updateInfo.latest}`:'检查更新'} aria-label="检查更新" onClick={checkUpdate} disabled={updateChecking}><RotateCw size={18}/>{updateInfo?.available&&<i/>}</button><button className="icon-btn" title="安装网页采集扩展" aria-label="安装网页采集扩展" onClick={()=>{setExtensionResult(null);setExtensionPanel(true)}}><Puzzle size={18}/></button><button className="icon-btn" title="自定义配色" aria-label="自定义配色" onClick={()=>setThemePanel(true)}><SlidersHorizontal size={18}/></button><button className="avatar" title="资源库健康与备份" onClick={showLibraryInfo}>N</button></header>
      <section className="toolbar"><div><h1>{activeFolder?currentFolder?.name:filter}</h1><span>{contentFolders.length} 个文件夹 · {shown.length} 个素材</span></div><div className="view-actions">{activeFolder&&<button onClick={()=>setActiveFolder(currentFolder?.parentId||null)}><FolderOpen size={15}/> 返回上级</button>}<button onClick={()=>addFolderAt(activeFolder)}><Plus size={15}/> 新建文件夹</button><button className={allShownSelected?'on':''} disabled={!shown.length} onClick={toggleSelectAll}><LayoutGrid size={15}/> {allShownSelected?'取消全选':'全选'}</button><button onClick={()=>setSortOrder(x=>x==='recent'?'name':'recent')}><ChevronDown size={15}/> {sortOrder==='recent'?'最近添加':'名称排序'}</button><button className="view-mode-button" title="切换视图" aria-label="切换视图" onClick={cycleViewMode}>{viewMode==='list'?<List size={17}/>:viewMode==='compact'?<Grid2X2 size={17}/>:<LayoutGrid size={17}/>}<span>{viewMode==='list'?'列表':viewMode==='compact'?'紧凑':'标准'}</span></button><button title="打开其他资源库" onClick={desktop?openLibrary:undefined}><MoreHorizontal size={18}/></button></div></section>
      {contentFolders.length>0&&<section className="content-folders">{contentFolders.map(folder=><button key={folder.id} className={dropFolderId===folder.id?'drop-target':''} onClick={()=>openFolder(folder)} onDoubleClick={()=>openFolder(folder)} onContextMenu={e=>{e.preventDefault();e.stopPropagation();setContextMenu({kind:'folder',x:e.clientX,y:e.clientY,folder})}} onDragOver={e=>{if(e.dataTransfer.types.includes(INTERNAL_DRAG)){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';setDropFolderId(folder.id)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDropFolderId(undefined)}} onDrop={e=>dropAssets(e,folder.id)}><FolderMark folder={folder}/><span><strong>{folder.name}</strong><small>{folderAssetCounts.get(folder.id)||0} 个素材</small></span><ChevronDown size={16}/></button>)}</section>}
      {shown.length?<section className="masonry" onPointerDown={beginMarquee} onPointerMove={moveMarquee} onPointerUp={endMarquee} onPointerCancel={endMarquee}>{displayed.map(a=><article key={a.id} data-asset-id={a.id} draggable={desktop} onDragStart={e=>startAssetDrag(e,a)} onDragEnd={()=>{externalDragActive.current=false;clearTimeout(externalDragTimer.current);setDropFolderId(undefined);setDrag(false)}} className={`${selected?.id===a.id?'selected':''} ${selectedIds.includes(a.id)?'multi-selected':''}`} onContextMenu={e=>{e.preventDefault();e.stopPropagation();setSelected(a);setContextMenu({x:e.clientX,y:e.clientY,asset:a})}} onDoubleClick={()=>{setPreviewId(a.id);resetPreviewView()}} onClick={e=>clickAsset(e,a)}><div className="thumb" draggable={desktop} onDragStart={e=>startAssetDrag(e,a)} title="拖到桌面、其他软件或浏览器上传区域"><Media asset={a} onSize={(width,height)=>{if(!a.width)patch(a.id,{width,height})}}/><button className="select-dot" aria-label="选择素材" onClick={e=>{e.stopPropagation();lastSelectedId.current=a.id;toggleSelected(a.id)}}>{selectedIds.includes(a.id)?'✓':''}</button><button aria-label={a.favorite?'取消收藏':'收藏'} title={a.favorite?'取消收藏':'收藏'} className={a.favorite?'fav yes':'fav'} onClick={e=>{e.stopPropagation();patch(a.id,{favorite:!a.favorite})}}><Heart size={17} fill={a.favorite?'currentColor':'none'}/></button><div className="dimensions">{a.width||'—'} × {a.height||'—'}</div></div><div className="meta" title="拖动名称可移动到内部文件夹"><strong>{a.name}</strong><div>{a.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div></div></article>)}</section>:!contentFolders.length&&<div className="empty"><ImageIcon size={34}/><h2>这里还没有素材或文件夹</h2><p>新建文件夹，或拖入图片、视频和外部文件夹。</p><button onClick={desktop?nativeImport:()=>input.current.click()}>选择图片</button></div>}
    </main>
    {marquee&&<div className="selection-marquee" style={marquee}/>} 
    {selected&&<Detail asset={assets.find(a=>a.id===selected.id)||selected} folders={orderedFolders} close={()=>setSelected(null)} patch={patch} del={del} open={openAssetAction} reveal={revealAsset} confirmAction={askConfirm}/>} 
    {(drag||importing)&&<div className="drop"><Import size={38}/><strong>{importing?'正在导入并检查重复素材…':'释放即可导入'}</strong><span>支持常用图片、视频、MP3、WAV、FLAC、M4A 等音频</span></div>}
    {message&&library&&<div className="toast">{message}</div>}
    {selectedIds.length>0&&desktop&&<div className="batch-bar"><strong>已选择 {selectedIds.length} 项</strong><button onClick={()=>batchUpdate({favorite:true})}><Heart size={15}/> 收藏</button><button onClick={batchTag}><Tag size={15}/> 标签</button><button onClick={batchMove}><Folder size={15}/> 移动</button><button className="danger" onClick={batchDelete}><Trash2 size={15}/> 删除</button><button aria-label="取消选择" onClick={()=>setSelectedIds([])}><X size={16}/></button></div>}
    {previewAsset&&<Preview asset={previewAsset} zoom={zoom} rotation={rotation} checker={checker} setZoom={setZoom} setRotation={setRotation} setChecker={setChecker} reset={resetPreviewView} close={()=>setPreviewId(null)} previous={()=>movePreview(-1)} next={()=>movePreview(1)}/>}
    {desktop&&ready&&!library&&<div className="welcome"><div className="welcome-card"><div className="mark big">N</div><h1>建立你的素材资源库</h1><p>资源库会在你选择的文件夹中保存原始素材和索引，可整体备份或迁移。</p>{message&&<span className="welcome-error">{message}</span>}<button className="primary" onClick={createLibrary}>创建资源库</button><button onClick={openLibrary}>打开已有资源库</button></div></div>}
    {contextMenu?.kind==='folder'?<FolderContextMenu menu={contextMenu} close={()=>setContextMenu(null)} actions={{open:()=>{setFilter('全部素材');setActiveFolder(contextMenu.folder.id);setSelected(null)},add:()=>addFolderAt(contextMenu.folder.id),rename:()=>renameFolder(contextMenu.folder),delete:()=>deleteFolder(contextMenu.folder)}}/>:contextMenu&&<AssetContextMenu menu={contextMenu} folders={orderedFolders} close={()=>setContextMenu(null)} actions={{open:()=>openAssetAction(contextMenu.asset.id),preview:()=>{setPreviewId(contextMenu.asset.id);setZoom(1)},tag:()=>contextTag(contextMenu.asset),note:()=>contextNote(contextMenu.asset),move:folderId=>contextMove(contextMenu.asset,folderId),duplicate:()=>duplicateAssetAction(contextMenu.asset.id),rename:()=>contextRename(contextMenu.asset),export:()=>exportAssetAction(contextMenu.asset.id),reveal:()=>revealAsset(contextMenu.asset.id),copyAsset:()=>copyAssetToClipboard(contextMenu.asset),copyFolder:async()=>{const result=await window.nestDesktop.copyAssetFolder(contextMenu.asset.id);setMessage(result?.error||'所在目录已复制');setTimeout(()=>setMessage(''),2500)},copyPath:async()=>{const result=await window.nestDesktop.copyAssetPath(contextMenu.asset.id);if(result?.error)setMessage(result.error);else{if(result?.library)applyLibrary(result.library);setMessage('文件路径已复制')}setTimeout(()=>setMessage(''),2500)},delete:()=>contextDelete(contextMenu.asset)}}/>}
    {dialogState&&<AppDialog state={dialogState} resolve={resolveDialog}/>} 
    {extensionPanel&&<ExtensionPanel busy={extensionBusy} result={extensionResult} install={prepareExtension} close={()=>setExtensionPanel(false)}/>} 
    {themePanel&&<ThemePanel color={themeColor} setColor={color=>{setThemeColor(color);localStorage.setItem(THEME_COLOR_KEY,color)}} close={()=>setThemePanel(false)}/>} 
    {updatePanel&&updateInfo&&<UpdatePanel info={updateInfo} progress={updateProgress} file={updateFile} error={updateError} close={()=>setUpdatePanel(false)} download={downloadUpdate} install={()=>window.nestDesktop.installUpdate(updateFile)}/>}
    <button className="bug-feedback" title="在软件内打开腾讯文档 Bug 反馈表" onClick={async()=>{const result=await window.nestDesktop?.openBugFeedback();if(result?.error){setMessage(result.error);setTimeout(()=>setMessage(''),4000)}}}><Bug size={16}/><span>Bug 反馈</span></button>
  </div>
}

function Detail({asset,folders=[],close,patch,del,open,reveal,confirmAction}){ const [tag,setTag]=useState(''); const add=()=>{if(tag.trim()){patch(asset.id,{tags:[...new Set([...(asset.tags||[]),tag.trim()])]});setTag('')}}; return <aside className="detail"><div className="detail-head"><strong>{asset.name}</strong><button aria-label="关闭详情" title="关闭 (Esc)" onClick={close}><X size={18}/></button></div><div className="detail-preview"><Media asset={asset} preview/></div><div className="detail-body"><input className="name-input" value={asset.name} onChange={e=>patch(asset.id,{name:e.target.value})}/><div className="rating" aria-label="评分">{[1,2,3,4,5].map(n=><button key={n} className={n<=(asset.rating||0)?'rated':''} onClick={()=>patch(asset.id,{rating:n===asset.rating?0:n})}>★</button>)}</div><div className="facts"><div><span>格式</span><b>{asset.type.split('/')[1]?.toUpperCase()}</b></div><div><span>尺寸</span><b>{asset.width||'—'} × {asset.height||'—'}</b></div><div><span>大小</span><b>{fmt(asset.size)}</b></div></div><label><Folder size={15}/> 所在文件夹</label><select className="folder-select" value={asset.folderId||''} onChange={e=>patch(asset.id,{folderId:e.target.value||null})}><option value="">未分类</option>{folders.map(f=><option key={f.id} value={f.id}>{'— '.repeat(f.depth)}{f.name}</option>)}</select><label><Tag size={15}/> 标签</label><div className="tags">{(asset.tags||[]).map(t=><button key={t} onClick={()=>patch(asset.id,{tags:asset.tags.filter(x=>x!==t)})}>{t}<X size={12}/></button>)}</div><div className="add-tag"><input placeholder="添加标签" value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add()}}/><button onClick={add}><Plus size={16}/></button></div><label><Info size={15}/> 备注</label><textarea placeholder="写下关于这个素材的想法…" value={asset.note||''} onChange={e=>patch(asset.id,{note:e.target.value})}/><div className="detail-actions"><button className="open" onClick={()=>open(asset.id)}>打开</button><button onClick={()=>reveal(asset.id)}>定位文件</button></div><button className="delete" onClick={async()=>{if(await confirmAction('删除这个素材？','原文件会移到系统回收站或废纸篓。'))del(asset.id)}}><Trash2 size={16}/> 删除素材</button></div></aside> }

function FolderMark({folder}){const Icon=folderIcon(folder.icon);return <Icon className="folder-glyph" size={16} style={{color:folder.color||'#9ba4ae'}}/>}

function AppDialog({state,resolve}){const isFolder=state.kind==='folder';const [value,setValue]=useState(state.defaultValue||''),[parentId,setParentId]=useState(state.parentId||''),[icon,setIcon]=useState('folder'),[color,setColor]=useState('#45c28b');const cancelValue=state.kind==='prompt'||isFolder?null:false;const submit=e=>{e.preventDefault();resolve(isFolder?{name:value.trim(),parentId:parentId||null,icon,color}:state.kind==='prompt'?value:true)};return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)resolve(cancelValue)}}><form className={`app-dialog ${isFolder?'folder-dialog':''}`} onSubmit={submit} onKeyDown={e=>{if(e.key==='Escape')resolve(cancelValue)}}><div className="dialog-head"><h2>{state.title}</h2><button type="button" aria-label="关闭" onClick={()=>resolve(cancelValue)}><X size={18}/></button></div>{state.detail&&<p>{state.detail}</p>}{(state.kind==='prompt'||isFolder)&&<div className="dialog-field"><label>{isFolder?'文件夹名称':'名称'}</label><div className="counted-input"><input autoFocus maxLength={isFolder?50:200} value={value} placeholder={state.placeholder||(isFolder?'输入文件夹名称':'请输入')} onChange={e=>setValue(e.target.value)}/>{isFolder&&<span>{value.length}/50</span>}</div></div>}{isFolder&&<><div className="dialog-field"><label>父级位置</label><select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">资源库根目录</option>{state.folders.map(f=><option value={f.id} key={f.id}>{'— '.repeat(f.depth)}{f.name}</option>)}</select></div><div className="dialog-field"><label>文件夹图标</label><div className="icon-picker">{FOLDER_ICONS.map(([key,Icon])=><button type="button" className={icon===key?'chosen':''} key={key} onClick={()=>setIcon(key)}><Icon size={20}/></button>)}</div></div><div className="dialog-field"><label>文件夹颜色</label><div className="color-picker">{FOLDER_COLORS.map(c=><button type="button" aria-label={`选择颜色 ${c}`} className={color===c?'chosen':''} style={{background:c}} key={c} onClick={()=>setColor(c)}>{color===c&&'✓'}</button>)}</div></div></>}<div className="dialog-actions"><button type="button" onClick={()=>resolve(cancelValue)}>取消</button><button className="primary" type="submit" disabled={(state.kind==='prompt'||isFolder)&&!value.trim()}>{isFolder?'创建':state.kind==='confirm'?'确认':'保存'}</button></div></form></div>}

function ExtensionPanel({busy,result,install,close}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)close()}}><div className="app-dialog extension-dialog"><div className="dialog-head"><h2>安装 Nest 网页采集器</h2><button aria-label="关闭" onClick={close} disabled={busy}><X size={18}/></button></div><p>选择浏览器后，Nest 会自动准备扩展、打开扩展管理页并复制扩展目录。</p><div className="browser-choices"><button disabled={busy} onClick={()=>install('chrome')}><b className="browser-logo chrome-logo">●</b><span><strong>Google Chrome</strong><small>安装到谷歌浏览器</small></span><ChevronDown size={18}/></button><button disabled={busy} onClick={()=>install('edge')}><b className="browser-logo edge-logo">e</b><span><strong>Microsoft Edge</strong><small>安装到 Edge 浏览器</small></span><ChevronDown size={18}/></button></div>{busy&&<div className="extension-status">正在准备扩展…</div>}{result?.ok&&<div className="extension-result success"><strong>扩展已准备好</strong><span>1. 在浏览器中打开“开发者模式”</span><span>2. 点击“加载已解压的扩展程序”，目录已复制并在资源管理器中打开</span><code>{result.path}</code></div>}{result&&!result.ok&&<div className="extension-result error"><strong>准备失败</strong><span>{result.error}</span>{result.path&&<code>{result.path}</code>}</div>}<div className="dialog-actions"><button onClick={close} disabled={busy}>{result?.ok?'完成':'取消'}</button></div></div></div>}

function ThemePanel({color,setColor,close}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="app-dialog theme-dialog"><div className="dialog-head"><h2>自定义配色</h2><button aria-label="关闭" onClick={close}><X size={18}/></button></div><p>选择主题强调色，按钮、选中状态和拖拽提示会立即更新。</p><div className="theme-swatches">{THEME_COLORS.map(item=><button key={item} className={color.toLowerCase()===item?'chosen':''} style={{background:item}} title={item} onClick={()=>setColor(item)}>{color.toLowerCase()===item&&'✓'}</button>)}</div><label className="custom-color"><span>自定义颜色</span><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><code>{color.toUpperCase()}</code></label><div className="theme-preview"><i style={{background:color}}/><span>当前主题色预览</span></div><div className="dialog-actions"><button onClick={()=>setColor('#267ff4')}>恢复默认</button><button className="primary" onClick={close}>完成</button></div></div></div>}
function UpdatePanel({info,progress,file,error,close,download,install}){const downloading=progress&&progress.percent<100&&!file;return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!downloading)close()}}><div className="app-dialog update-dialog"><div className="dialog-head"><h2>{info.available?'发现新版本':'已经是最新版'}</h2><button aria-label="关闭" disabled={downloading} onClick={close}><X size={18}/></button></div><div className="update-versions"><span>当前版本 <b>v{info.current}</b></span><i>→</i><span>最新版本 <b>v{info.latest}</b></span></div>{info.available?<><p>{info.downloadName?`已识别为${info.installKind}：${info.downloadName}`:'当前版本暂未提供适合此设备的安装包。'}</p>{progress&&<div className="update-progress"><div><i style={{width:`${progress.percent||0}%`}}/></div><span>{file?'下载完成':`正在下载 ${Math.round(progress.percent||0)}%`}</span><small>{progress.total?`${fmt(progress.received)} / ${fmt(progress.total)}`:file?'可以开始安装':'正在连接下载服务器…'}</small></div>}{error&&<p className="update-error">{error}</p>}{!progress&&info.notes&&<pre>{info.notes}</pre>}<div className="dialog-actions"><button onClick={close} disabled={downloading}>稍后提醒</button>{file?<button className="primary" onClick={install}><Download size={16}/> 安装更新</button>:<button className="primary" onClick={download} disabled={downloading||!info.downloadName}><Download size={16}/> {downloading?'正在下载':'立即更新'}</button>}</div></>:<><p>当前安装的版本已经是 GitHub 上发布的最新版本。</p><div className="dialog-actions"><button className="primary" onClick={close}>知道了</button></div></>}</div></div>}

function AssetContextMenu({menu,folders,actions,close}){const [moving,setMoving]=useState(false);const run=fn=>{close();fn()};const rows=[[FolderOpen,'打开',actions.open],[Eye,'快速预览',actions.preview],[Tag,'添加标签',actions.tag],[StickyNote,'添加注释',actions.note]];return <div className="asset-menu" style={{left:Math.min(menu.x,window.innerWidth-250),top:Math.min(menu.y,window.innerHeight-520)}} onClick={e=>e.stopPropagation()} onContextMenu={e=>e.preventDefault()}>{rows.map(([Icon,label,fn])=><button key={label} onClick={()=>run(fn)}><Icon size={16}/><span>{label}</span></button>)}<div className="menu-separator"/><button onClick={()=>setMoving(x=>!x)}><Folder size={16}/><span>移动到文件夹</span><b>›</b></button>{moving&&<div className="move-submenu"><button onClick={()=>run(()=>actions.move(null))}><Archive size={15}/>未分类</button>{folders.map(f=><button key={f.id} style={{paddingLeft:12+f.depth*12}} onClick={()=>run(()=>actions.move(f.id))}><FolderMark folder={f}/>{f.name}</button>)}</div>}<button onClick={()=>run(actions.duplicate)}><Copy size={16}/><span>复制素材</span></button><button onClick={()=>run(actions.rename)}><Pencil size={16}/><span>重命名</span></button><div className="menu-separator"/><button onClick={()=>run(actions.copyAsset)}><ClipboardCopy size={16}/><span>复制文件</span></button><button onClick={()=>run(actions.copyFolder)}><Folder size={16}/><span>复制所在目录</span></button><button onClick={()=>run(actions.copyPath)}><ClipboardCopy size={16}/><span>复制完整路径</span></button><button onClick={()=>run(actions.export)}><Download size={16}/><span>导出原始文件</span></button><button onClick={()=>run(actions.reveal)}><FolderOpen size={16}/><span>在资源管理器中显示</span></button><div className="menu-separator"/><button className="menu-danger" onClick={()=>run(actions.delete)}><Trash2 size={16}/><span>删除</span></button></div>}

function FolderContextMenu({menu,actions,close}){const run=fn=>{close();fn()};return <div className="asset-menu folder-menu" style={{left:Math.min(menu.x,window.innerWidth-230),top:Math.min(menu.y,window.innerHeight-190)}} onClick={e=>e.stopPropagation()} onContextMenu={e=>e.preventDefault()}><button onClick={()=>run(actions.open)}><FolderOpen size={16}/><span>打开文件夹</span></button><button onClick={()=>run(actions.add)}><Plus size={16}/><span>新建子文件夹</span></button><div className="menu-separator"/><button onClick={()=>run(actions.rename)}><Pencil size={16}/><span>重命名</span></button><button className="menu-danger" onClick={()=>run(actions.delete)}><Trash2 size={16}/><span>删除文件夹</span></button></div>}

function Preview({asset,zoom,rotation,checker,setZoom,setRotation,setChecker,reset,close,previous,next}){const image=asset.type?.startsWith('image');return <div className="preview-overlay" onWheel={e=>{if(!image)return;e.preventDefault();setZoom(z=>Math.min(4,Math.max(.25,z+(e.deltaY<0?.25:-.25))))}}><div className="preview-top"><strong>{asset.name}</strong>{image&&<><button title="适应窗口" onClick={reset}><Maximize2 size={17}/>适应</button><button title="向右旋转 90°" onClick={()=>setRotation(r=>(r+90)%360)}><RotateCw size={17}/>旋转</button><button className={checker?'on':''} title="透明背景" onClick={()=>setChecker(v=>!v)}><i className="checker-icon"/>透明背景</button><button title="缩小" onClick={()=>setZoom(z=>Math.max(.25,z-.25))}>−</button><b>{Math.round(zoom*100)}%</b><button title="放大" onClick={()=>setZoom(z=>Math.min(4,z+.25))}>＋</button></>}<button title="关闭 (Esc)" onClick={close}><X size={20}/></button></div><button className="preview-arrow left" title="上一个 (←)" onClick={previous}>‹</button><div className={`preview-stage ${checker?'checker':''}`}><Media asset={asset} preview style={image?{transform:`scale(${zoom}) rotate(${rotation}deg)`}:undefined}/></div><button className="preview-arrow right" title="下一个 (→)" onClick={next}>›</button></div>}

const durationText=value=>{if(!Number.isFinite(value))return'';const seconds=Math.round(value);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`};
function AudioWaveform({src,large=false}){const canvasRef=useRef(null);useEffect(()=>{if(!src)return;const controller=new AbortController();let context;const draw=async()=>{try{const response=await fetch(src,{signal:controller.signal});const bytes=await response.arrayBuffer();const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;context=new AudioCtx();const buffer=await context.decodeAudioData(bytes.slice(0));if(controller.signal.aborted)return;const samples=buffer.getChannelData(0),canvas=canvasRef.current;if(!canvas)return;const width=large?720:300,height=large?150:92,dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);const columns=large?180:88,step=Math.max(1,Math.floor(samples.length/columns)),barWidth=width/columns;ctx.fillStyle=large?'#77a9f5':'#9299a2';for(let i=0;i<columns;i++){let peak=0;const start=i*step,end=Math.min(samples.length,start+step);for(let j=start;j<end;j+=Math.max(1,Math.floor(step/80)))peak=Math.max(peak,Math.abs(samples[j]));const h=Math.max(2,peak*(height-8));ctx.fillRect(i*barWidth,(height-h)/2,Math.max(1,barWidth-1),h)}}catch(error){if(error.name!=='AbortError')console.warn('Audio waveform:',error.message)}finally{context?.close?.()}};draw();return()=>{controller.abort();context?.close?.()}},[src,large]);return <canvas ref={canvasRef} className="audio-waveform" aria-hidden="true"/>}
function AudioMedia({asset,preview=false,style}){const [duration,setDuration]=useState(null),[current,setCurrent]=useState(0),[progress,setProgress]=useState(0),audioRef=useRef(null),pointerRef=useRef({ratio:-1,at:0});const format=(asset.type?.split('/')[1]||asset.name.split('.').pop()||'audio').replace('mpeg','mp3').toUpperCase();const bpm=asset.name.match(/(?:^|[\s_\-])BPM[\s_\-:]*(\d{2,3})(?:\D|$)/i)?.[1];const updateProgress=e=>{const audio=e.currentTarget;setCurrent(audio.currentTime||0);setProgress(audio.duration?audio.currentTime/audio.duration:0)};const enter=()=>{if(!preview)audioRef.current?.play().catch(()=>{})};const seekAtPointer=e=>{const audio=audioRef.current;if(preview||!audio||!Number.isFinite(audio.duration)||audio.duration<=0)return;const rect=e.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),now=performance.now(),last=pointerRef.current;if(now-last.at<75||Math.abs(ratio-last.ratio)<.012)return;pointerRef.current={ratio,at:now};const time=ratio*audio.duration;audio.currentTime=time;setCurrent(time);setProgress(ratio)};const leave=()=>{if(!preview&&audioRef.current){audioRef.current.pause();audioRef.current.currentTime=0;pointerRef.current={ratio:-1,at:0};setCurrent(0);setProgress(0)}};return <div className={`audio-media ${preview?'preview':''}`} style={style} onMouseEnter={enter} onMouseLeave={leave}><div className="audio-wave-card" onPointerMove={seekAtPointer}><span className="audio-badge">{format}{bpm?` / BPM: ${bpm}`:''}</span>{duration!==null&&<span className="audio-duration">{durationText(current)} / {durationText(duration)}</span>}<AudioWaveform src={asset.url} large={preview}/><i className="audio-play-depth" style={{width:`${progress*100}%`}}/></div>{preview?<><span>{asset.name}</span>{duration!==null&&<small>时长 {durationText(duration)} · {format}</small>}<audio ref={audioRef} src={asset.url} controls preload="metadata" draggable={false} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onTimeUpdate={updateProgress}/></>:<audio ref={audioRef} className="audio-hover-player" src={asset.url} preload="metadata" draggable={false} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onTimeUpdate={updateProgress} onEnded={()=>{setCurrent(0);setProgress(0)}}/>}</div>}
function Media({asset,preview=false,onSize,style}){if(asset.type?.startsWith('audio'))return <AudioMedia asset={asset} preview={preview} style={style}/>;return asset.type?.startsWith('video')?<video src={asset.url} controls={preview} muted={!preview} loop={!preview} playsInline preload="metadata" style={style} onLoadedMetadata={e=>{onSize?.(e.currentTarget.videoWidth,e.currentTarget.videoHeight);if(!preview&&Number.isFinite(e.currentTarget.duration)&&e.currentTarget.duration>.1)e.currentTarget.currentTime=.1}}/>:<img src={asset.url||undefined} alt={asset.name||''} draggable={false} loading={preview?'eager':'lazy'} style={style} onLoad={e=>onSize?.(e.currentTarget.naturalWidth,e.currentTarget.naturalHeight)}/>}

createRoot(document.getElementById('root')).render(<App/>);
